# Generated by Django 4.1.1 on 2022-09-23 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(db_index=True, max_length=64, verbose_name='Id чата с пользователем')),
                ('username', models.CharField(max_length=32, verbose_name='Username пользователя из Telegram')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя пользователя')),
                ('last_name', models.CharField(max_length=64, verbose_name='Фамилия пользователя')),
                ('phone_number', models.CharField(blank=True, default='', max_length=16, verbose_name='Номер телефона')),
                ('bot_status', models.IntegerField(default=0)),
                ('preference', models.CharField(choices=[('a', 'all'), ('u', 'usual'), ('v', 'vegeterian'), ('k', 'for kids')], default='a', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=None)),
                ('description', models.TextField(max_length=255)),
                ('category', models.CharField(choices=[('u', 'usual'), ('v', 'vegeterian'), ('k', 'for kids')], max_length=10)),
                ('reaction', models.CharField(choices=[('l', 'like'), ('d', 'dislike'), ('i', 'indifferent')], max_length=10)),
                ('chats', models.ManyToManyField(blank=True, related_name='recipes', to='recipe_bot.chat')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('measure', models.CharField(max_length=10)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipe_bot.recipe')),
            ],
        ),
    ]
