# Generated by Django 4.1.1 on 2022-09-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='chat',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Номер телефона пользователя'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='username',
            field=models.CharField(blank=True, max_length=128, verbose_name='Username пользователя'),
        ),
    ]
