# Generated by Django 4.1.1 on 2022-09-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_bot', '0002_remove_chat_first_name_remove_chat_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='bot_status',
        ),
        migrations.AddField(
            model_name='chat',
            name='dialogue_stage',
            field=models.IntegerField(default=0, verbose_name='Этап диалога с ботом'),
        ),
    ]
