# Generated by Django 3.1.14 on 2022-09-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_bot', '0002_auto_20220923_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='title',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('u', 'usual'), ('v', 'vegeterian'), ('k', 'for kids'), ('d', 'dietary'), ('a', 'vegan')], max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='reaction',
            field=models.CharField(choices=[('l', 'like'), ('d', 'dislike'), ('i', 'indifferent')], default='i', max_length=10),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
