# Generated by Django 3.1.14 on 2022-09-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_bot', '0004_auto_20220924_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(default='a', max_length=255),
        ),
    ]
