# Generated by Django 3.1.14 on 2022-09-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_bot', '0005_auto_20220924_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(default='a', max_length=255, null=True),
        ),
    ]
