# Generated by Django 4.0.4 on 2022-09-24 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_bot', '0003_remove_chat_bot_status_chat_dialogue_stage'),
        ('recipe_bot', '0006_auto_20220924_1108'),
    ]

    operations = [
    ]
