# Generated by Django 3.1.14 on 2022-09-25 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_bot', '0007_merge_20220925_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.CharField(default='', max_length=255),
        ),
    ]
